version: '3'

services:
  mongo_db:
    container_name: database_container 
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo-admin
      MONGO_INITDB_ROOT_PASSWORD: 5abc0e832a2279f2c1b32bbfec2637676184dd85
    volumes:
      - ./mongo-db:/data/db
    ports:
      - 27017:27017